/**
 * Ordinary days across all three years.
 *
 * Real journals are mostly this: short entries about nothing much. These bring
 * the significance distribution into a believable shape (routine 30-40%) and
 * give the density that makes gaps in the timeline read as gaps rather than as
 * missing data. Narratives are deliberately brief — a one-line day does not
 * warrant a paragraph.
 */

export const MEMORIES_ROUTINE = [
  /* ===================================================== 2024 ==== */
  { date: "2024-01-31T08:00:00+05:30", place: "pune_home", text: "Chai on the balcony before anyone else was awake. The whole building silent for once.", description: "A short note about an early quiet morning.", tags: ["morning", "quiet"], sentiment: { valence: 0.45, energy: 0.25, label: "calm", confidence: 0.82 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "What made the silence notable?", answer: "It never lasts past seven.", narrative: "Chai on the balcony before anyone was awake, the whole building silent. It never lasts past seven." },
  { date: "2024-02-11T19:00:00+05:30", place: "pune_camp", text: "Bought vegetables from the man who always overcharges me and always throws in extra coriander.", description: "A short note about a familiar market transaction.", tags: ["market", "routine"], sentiment: { valence: 0.4, energy: 0.35, label: "calm", confidence: 0.78 }, lifeThemes: ["daily-life", "food"], eventType: "ordinary-moment", significance: "routine", question: "Do you mind the overcharging?", answer: "Not really. The coriander is good.", narrative: "Vegetables from the man who always overcharges me and always throws in extra coriander. I've stopped minding." },
  { date: "2024-03-05T22:00:00+05:30", place: "pune_home", text: "Reread a book I last read at nineteen. Different book entirely now.", description: "A short note about rereading a familiar book.", tags: ["books", "rereading"], sentiment: { valence: 0.5, energy: 0.3, label: "nostalgic", confidence: 0.85 }, lifeThemes: ["hobbies"], eventType: "reflection", significance: "routine", question: "What changed?", answer: "I sided with a different character this time.", narrative: "Reread a book I last read at nineteen and found a different book entirely. I sided with a different character this time." },
  { date: "2024-03-29T18:30:00+05:30", place: "pune_fcroad", text: "Waited fifty minutes for a bus that came in four minutes after I gave up and started walking.", description: "A short note about waiting for public transport.", tags: ["commute", "waiting"], sentiment: { valence: -0.35, energy: 0.4, label: "frustrated", confidence: 0.8 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "Did you see it pass you?", answer: "Yes. From the pavement. It was almost funny.", narrative: "Waited fifty minutes for a bus that arrived four minutes after I gave up and started walking. I watched it pass me from the pavement." },
  { date: "2024-04-14T12:00:00+05:30", place: "pune_home", text: "Attempted Amma's rasam from memory. It was rasam-adjacent.", description: "A short note about an unsuccessful cooking attempt.", tags: ["food", "cooking"], sentiment: { valence: 0.15, energy: 0.4, label: "uncertain", confidence: 0.76 }, lifeThemes: ["food", "family"], eventType: "ordinary-moment", significance: "routine", question: "What did you get wrong?", answer: "Everything after the tamarind.", narrative: "Attempted Amma's rasam from memory. It was rasam-adjacent. Everything after the tamarind went wrong." },
  { date: "2024-05-02T20:00:00+05:30", place: "pune_home", text: "Power cut during the hottest week of the year. Sat in the dark with a wet towel and a book I couldn't read.", description: "A short note about a power cut in summer.", tags: ["summer", "home"], sentiment: { valence: -0.3, energy: 0.3, label: "frustrated", confidence: 0.8 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "How long did it last?", answer: "Three hours. Felt longer.", narrative: "Power cut during the hottest week of the year. Three hours in the dark with a wet towel and a book I couldn't read." },
  { date: "2024-06-02T09:00:00+05:30", place: "pune_tekdi", text: "Same walk, same hill, same three dogs at the top who have never once acknowledged me.", description: "A short note about a habitual walk.", tags: ["walking", "routine"], sentiment: { valence: 0.35, energy: 0.4, label: "calm", confidence: 0.8 }, lifeThemes: ["health"], eventType: "ordinary-moment", significance: "routine", question: "Do you want them to?", answer: "A little.", narrative: "Same walk, same hill, same three dogs at the top who have never once acknowledged me. I'd like them to." },
  { date: "2024-07-06T21:00:00+05:30", place: "pune_home", text: "Watched the rain from the window for an hour instead of doing anything. No regrets.", description: "A short note about watching rain.", tags: ["monsoon", "rest"], sentiment: { valence: 0.55, energy: 0.2, label: "calm", confidence: 0.86 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "Were you supposed to be doing something?", answer: "Always.", narrative: "Watched the rain from the window for an hour instead of doing anything I was supposed to. No regrets." },
  { date: "2024-08-23T14:00:00+05:30", place: "pune_aundh", text: "Haircut. Asked for the same as last time, got something else entirely, said it looked great.", description: "A short note about a haircut.", tags: ["errands"], sentiment: { valence: 0.05, energy: 0.35, label: "uncertain", confidence: 0.74 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "Did it look great?", answer: "It looked fine in about nine days.", narrative: "Asked for the same haircut as last time, got something else entirely, said it looked great. It did look fine, in about nine days." },
  { date: "2024-09-08T11:30:00+05:30", place: "pune_kp", text: "Sunday market. Bought a plant I have no plan for and a bag of mangoes that were past their best.", description: "A short note about a market visit.", tags: ["market", "sunday"], sentiment: { valence: 0.42, energy: 0.45, label: "joyful", confidence: 0.8 }, lifeThemes: ["daily-life", "food"], eventType: "ordinary-moment", significance: "routine", question: "Does the plant still exist?", answer: "Barely.", narrative: "Sunday market — a plant I had no plan for and mangoes that were past their best. The plant barely still exists." },
  { date: "2024-10-30T20:00:00+05:30", place: "pune_home", text: "Fixed the tap that has been dripping since March. Took eleven minutes. Eleven minutes and seven months.", description: "A short note about a delayed repair.", tags: ["home", "procrastination"], sentiment: { valence: 0.3, energy: 0.4, label: "relieved", confidence: 0.82 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "Why did it take seven months?", answer: "I'd stopped hearing it.", narrative: "Fixed the tap that had dripped since March. Eleven minutes of work and seven months of not hearing it." },
  { date: "2024-11-09T19:30:00+05:30", place: "pune_camp", text: "Old film at the single-screen. Eleven people in the audience and one of them narrating it to his wife throughout.", description: "A short note about a cinema visit.", tags: ["film", "pune"], sentiment: { valence: 0.5, energy: 0.4, label: "joyful", confidence: 0.83 }, lifeThemes: ["hobbies"], eventType: "ordinary-moment", significance: "routine", question: "Was the narration annoying?", answer: "For ten minutes. Then it was the best part.", narrative: "An old film at the single-screen, eleven people in the audience, one narrating throughout to his wife. Annoying for ten minutes and then the best part." },
  { date: "2024-12-05T08:30:00+05:30", place: "pune_home", text: "First morning of the year cold enough for a second layer. The city looks embarrassed about it.", description: "A short note about the arrival of winter.", tags: ["winter", "pune"], sentiment: { valence: 0.4, energy: 0.35, label: "calm", confidence: 0.8 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "How cold is cold here?", answer: "Twelve degrees and everyone acts like it's an emergency.", narrative: "First morning cold enough for a second layer. Twelve degrees, and the whole city acting like an emergency." },

  /* ===================================================== 2025 ==== */
  { date: "2025-01-12T13:00:00+05:30", place: "pune_kp", text: "Lunch alone with a book. Waiter kept checking whether someone was joining me.", description: "A short note about eating alone.", tags: ["food", "solitude"], sentiment: { valence: 0.3, energy: 0.3, label: "calm", confidence: 0.8 }, lifeThemes: ["food"], eventType: "ordinary-moment", significance: "routine", question: "Did it bother you?", answer: "Only that he seemed worried about it.", narrative: "Lunch alone with a book. The waiter kept checking whether someone was joining me, and seemed genuinely concerned that nobody was." },
  { date: "2025-02-02T17:00:00+05:30", place: "pune_aundh", text: "Bought a pen I did not need because the shop had good light and I was in no hurry.", description: "A short note about an unnecessary purchase.", tags: ["objects", "browsing"], sentiment: { valence: 0.5, energy: 0.35, label: "joyful", confidence: 0.78 }, lifeThemes: ["hobbies", "finance"], eventType: "ordinary-moment", significance: "routine", question: "Do you still have it?", answer: "It's my favourite one.", narrative: "Bought a pen I did not need because the shop had good light and I was in no hurry. It became my favourite one." },
  { date: "2025-03-04T22:30:00+05:30", place: "pune_home", text: "Couldn't sleep. Reorganised every file on the laptop instead. Productive in the least useful possible way.", description: "A short note about insomnia.", tags: ["sleeplessness", "avoidance"], sentiment: { valence: -0.2, energy: 0.5, label: "uncertain", confidence: 0.78 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "Did it help you sleep?", answer: "No. But the files are still tidy.", narrative: "Couldn't sleep, so I reorganised every file on the laptop. It didn't help, but the files are still tidy." },
  { date: "2025-04-06T10:00:00+05:30", place: "pune_tekdi", text: "Ran into someone from school at the top of the hill. Neither of us could remember the other's name and we talked for twenty minutes anyway.", description: "A short note about an unexpected meeting.", tags: ["chance", "walking"], sentiment: { valence: 0.55, energy: 0.5, label: "joyful", confidence: 0.84 }, lifeThemes: ["friends"], eventType: "ordinary-moment", significance: "routine", question: "Did you ever work out the name?", answer: "On the way down. Too late to use it.", narrative: "Ran into someone from school at the top of the hill. Neither of us could remember the other's name and we talked for twenty minutes anyway. His name came to me on the way down." },
  { date: "2025-05-25T20:00:00+05:30", place: "pune_home", text: "Ate the same thing for dinner four nights running and only noticed on the fourth.", description: "A short note about repetitive cooking.", tags: ["food", "routine"], sentiment: { valence: 0.0, energy: 0.25, label: "neutral", confidence: 0.75 }, lifeThemes: ["food", "daily-life"], eventType: "ordinary-moment", significance: "routine", question: "Did you change it on the fifth?", answer: "No.", narrative: "Ate the same dinner four nights running and only noticed on the fourth. I did not change it on the fifth." },
  { date: "2025-06-08T16:00:00+05:30", place: "pune_camp", text: "The old bookshop near Camp has closed. There's a phone shop there now, which is exactly what you'd expect and still annoying.", description: "A short note about a closed shop.", tags: ["books", "pune", "change"], sentiment: { valence: -0.4, energy: 0.35, label: "disappointed", confidence: 0.85 }, lifeThemes: ["daily-life"], eventType: "loss", significance: "notable", question: "How long had it been there?", answer: "Longer than me.", narrative: "The old bookshop near Camp has closed and become a phone shop, which is exactly what you'd expect and still annoying. It had been there longer than I have." },
  { date: "2025-07-19T09:00:00+05:30", place: "pune_home", text: "Woke to find the plant from last September has produced one flower, entirely without my help.", description: "A short note about an unexpectedly flowering plant.", tags: ["plants", "home"], sentiment: { valence: 0.62, energy: 0.4, label: "joyful", confidence: 0.86 }, lifeThemes: ["hobbies"], eventType: "discovery", significance: "routine", question: "Had you been caring for it?", answer: "Not meaningfully.", narrative: "The plant from last September has produced one flower, entirely without my help and arguably in spite of it." },
  { date: "2025-08-05T18:00:00+05:30", place: "pune_fcroad", text: "Queued forty minutes for the ice cream place everyone talks about. It was fine. It was ice cream.", description: "A short note about a much-hyped food place.", tags: ["food", "queue"], sentiment: { valence: -0.1, energy: 0.4, label: "disappointed", confidence: 0.8 }, lifeThemes: ["food"], eventType: "ordinary-moment", significance: "routine", question: "Would you queue again?", answer: "No. But I'd have wondered forever otherwise.", narrative: "Queued forty minutes for the ice cream everyone talks about. It was fine. It was ice cream. But I'd have wondered forever otherwise." },
  { date: "2025-09-01T07:30:00+05:30", place: "pune_tekdi", text: "Monsoon light on the hill at seven. Photographed it badly, twice.", description: "A short note about morning light.", tags: ["monsoon", "morning", "photos"], sentiment: { valence: 0.6, energy: 0.35, label: "calm", confidence: 0.85 }, lifeThemes: ["health", "hobbies"], eventType: "ordinary-moment", significance: "routine", question: "Why badly?", answer: "It doesn't photograph. I keep trying anyway.", narrative: "Monsoon light on the hill at seven. Photographed it badly twice, as I do every year, because it doesn't photograph and I keep trying anyway." },
  { date: "2025-09-22T21:00:00+05:30", place: "pune_home", text: "Long call with Amma about nothing. Nine minutes on a neighbour's renovation.", description: "A short note about an unhurried family call.", tags: ["family", "calls"], sentiment: { valence: 0.55, energy: 0.3, label: "calm", confidence: 0.86 }, lifeThemes: ["family"], eventType: "ordinary-moment", significance: "routine", question: "What made it good?", answer: "Neither of us needed anything.", narrative: "Long call with Amma about nothing, including nine minutes on a neighbour's renovation. Neither of us needed anything, which is what made it good." },
  { date: "2025-10-05T15:00:00+05:30", place: "pune_kothrud", text: "Spent the afternoon rearranging the room to avoid preparing the talk. The room looks great.", description: "A short note about productive procrastination.", tags: ["avoidance", "home"], sentiment: { valence: 0.1, energy: 0.55, label: "uncertain", confidence: 0.78 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "Did the room stay that way?", answer: "Until roughly November.", narrative: "Spent an afternoon rearranging the room to avoid preparing the talk. The room looked great until roughly November." },
  { date: "2025-11-16T12:00:00+05:30", place: "pune_kp", text: "Winter sun and nothing to do. Sat outside for two hours and read forty pages.", description: "A short note about an unhurried afternoon.", tags: ["winter", "books", "rest"], sentiment: { valence: 0.6, energy: 0.25, label: "calm", confidence: 0.87 }, lifeThemes: ["hobbies"], eventType: "ordinary-moment", significance: "routine", question: "Forty pages in two hours?", answer: "I kept stopping to look at things.", narrative: "Winter sun and nothing to do. Two hours outside and forty pages, because I kept stopping to look at things." },
  { date: "2025-12-13T19:00:00+05:30", place: "pune_camp", text: "Bought a second-hand desk chair from a man who insisted on demonstrating every adjustment lever.", description: "A short note about buying second-hand furniture.", tags: ["home", "second-hand"], sentiment: { valence: 0.45, energy: 0.45, label: "joyful", confidence: 0.8 }, lifeThemes: ["daily-life", "finance"], eventType: "ordinary-moment", significance: "routine", question: "How many levers were there?", answer: "Five. He demonstrated each one twice.", narrative: "Bought a second-hand desk chair from a man who demonstrated all five adjustment levers, twice each. I have used one of them." },

  /* ===================================================== 2026 ==== */
  { date: "2026-01-04T09:00:00+05:30", place: "pune_home", text: "New year, no list this time. Just kept working on the thing I was already working on.", description: "A short note about starting the year without resolutions.", tags: ["intentions", "project"], sentiment: { valence: 0.5, energy: 0.45, label: "calm", confidence: 0.84 }, lifeThemes: ["personal-growth"], eventType: "decision", significance: "notable", question: "Why no list?", answer: "The last two lists were the same list.", narrative: "No list this year. The last two were the same list, so I just kept working on the thing I was already working on." },
  { date: "2026-01-18T14:00:00+05:30", place: "pune_aundh", text: "Bicycle service, finally. The man looked at the chain and made a noise I did not enjoy.", description: "A short note about a bicycle repair.", tags: ["errands", "cycling"], sentiment: { valence: 0.1, energy: 0.4, label: "uncertain", confidence: 0.77 }, lifeThemes: ["health", "finance"], eventType: "ordinary-moment", significance: "routine", question: "How bad was it?", answer: "Nine hundred rupees of bad.", narrative: "Bicycle service, long overdue. The mechanic looked at the chain and made a noise I did not enjoy. Nine hundred rupees of bad." },
  { date: "2026-02-01T20:00:00+05:30", place: "pune_home", text: "Cooked properly for the first time in weeks. Three dishes, one of which worked.", description: "A short note about cooking.", tags: ["food", "cooking"], sentiment: { valence: 0.35, energy: 0.45, label: "calm", confidence: 0.8 }, lifeThemes: ["food"], eventType: "ordinary-moment", significance: "routine", question: "Which one worked?", answer: "The simplest one. It always is.", narrative: "Cooked properly for the first time in weeks — three dishes, one of which worked. It was the simplest one. It always is." },
  { date: "2026-02-28T18:00:00+05:30", place: "pune_fcroad", text: "Ran into two people from the course by accident and we stood on the pavement for an hour.", description: "A short note about an unplanned meeting with friends.", tags: ["friends", "chance"], sentiment: { valence: 0.68, energy: 0.55, label: "joyful", confidence: 0.87 }, lifeThemes: ["friends"], eventType: "ordinary-moment", significance: "routine", question: "Did anyone suggest sitting down?", answer: "Three times. We never did.", narrative: "Ran into two people from the course and stood on the pavement for an hour. Someone suggested sitting down three times and we never did." },
  { date: "2026-03-08T11:00:00+05:30", place: "pune_kp", text: "Sunday. Nothing happened. Wrote that down anyway because most Sundays are this and I never keep them.", description: "A short note about an uneventful Sunday.", tags: ["sunday", "ordinary"], sentiment: { valence: 0.4, energy: 0.2, label: "reflective", confidence: 0.84 }, lifeThemes: ["daily-life"], eventType: "ordinary-moment", significance: "routine", question: "Why keep it?", answer: "Because I have no record of any of the others.", narrative: "A Sunday where nothing happened. I wrote it down because most Sundays are this one and I have no record of any of the others." },
  { date: "2026-04-02T21:00:00+05:30", place: "pune_home", text: "Project has a name now. Took four months and I chose it in about nine seconds.", description: "A short note about naming a project.", tags: ["project", "naming"], sentiment: { valence: 0.65, energy: 0.6, label: "proud", confidence: 0.86 }, lifeThemes: ["hobbies"], eventType: "decision", significance: "notable", question: "What decided it?", answer: "It described the thing instead of describing a mood.", narrative: "The project has a name. Four months of circling it and then nine seconds, because this one described the thing rather than a mood." },
  { date: "2026-04-24T08:00:00+05:30", place: "pune_tekdi", text: "Cycled to the hill and walked up it, which is the most virtuous I have ever been before nine in the morning.", description: "A short note about combined exercise.", tags: ["health", "morning"], sentiment: { valence: 0.6, energy: 0.65, label: "proud", confidence: 0.83 }, lifeThemes: ["health"], eventType: "ordinary-moment", significance: "routine", question: "Did you keep it up?", answer: "Twice more that month.", narrative: "Cycled to the hill and walked up it — the most virtuous I have been before nine in the morning. I managed it twice more that month." },
  { date: "2026-05-06T19:00:00+05:30", place: "pune_camp", text: "Bought a notebook to replace the one that ran out. Same brand, fourth year running.", description: "A short note about replacing a notebook.", tags: ["objects", "habit"], sentiment: { valence: 0.45, energy: 0.3, label: "calm", confidence: 0.82 }, lifeThemes: ["daily-life", "hobbies"], eventType: "ordinary-moment", significance: "routine", question: "Why the same brand?", answer: "The paper takes fountain pen without bleeding. That's the whole reason.", narrative: "Replaced the notebook that ran out, same brand for the fourth year running. The paper takes fountain pen without bleeding, which is the entire reason." },
  { date: "2026-06-14T13:00:00+05:30", place: "pune_kothrud", text: "Family lunch. Told them about the application. Appa said 'good' and then asked about the bicycle.", description: "A short note about family lunch.", tags: ["family", "food"], sentiment: { valence: 0.5, energy: 0.4, label: "joyful", confidence: 0.83 }, lifeThemes: ["family"], eventType: "ordinary-moment", significance: "routine", question: "Was that disappointing?", answer: "No. He asks about the bicycle when he's pleased.", narrative: "Told the family about the application at lunch. Appa said good and then asked about the bicycle, which is what he does when he's pleased." },
  { date: "2026-07-02T17:30:00+05:30", place: "pune_home", text: "Rain all day. Read the whole afternoon and made no attempt to do anything else.", description: "A short note about a rainy afternoon.", tags: ["monsoon", "books", "rest"], sentiment: { valence: 0.58, energy: 0.2, label: "calm", confidence: 0.86 }, lifeThemes: ["hobbies"], eventType: "ordinary-moment", significance: "routine", question: "What were you reading?", answer: "Something I'd started in 2024 and abandoned twice.", narrative: "Rain all day, so I read the whole afternoon and made no attempt at anything else. It was a book I'd started in 2024 and abandoned twice." },
  { date: "2026-08-13T20:00:00+05:30", place: "pune_home", text: "Told R about the offer. He said he'd been waiting two years to hear me sound like that.", description: "A short note about sharing good news with a friend.", tags: ["friends", "news"], sentiment: { valence: 0.75, energy: 0.55, label: "joyful", confidence: 0.9 }, lifeThemes: ["friends", "career"], eventType: "celebration", significance: "notable", question: "Sound like what?", answer: "He didn't elaborate and I didn't ask.", narrative: "Told R about the offer and he said he'd been waiting two years to hear me sound like that. He didn't elaborate and I didn't ask." },
  { date: "2026-08-27T07:00:00+05:30", place: "pune_tekdi", text: "Last quiet morning before everything changes. Same hill, same dogs. Still no acknowledgement.", description: "A short note about a walk before a life change.", tags: ["walking", "transition"], sentiment: { valence: 0.5, energy: 0.35, label: "nostalgic", confidence: 0.87 }, lifeThemes: ["health", "personal-growth"], eventType: "transition", significance: "notable", question: "What changes?", answer: "New job starts Monday. Everything and probably nothing.", narrative: "Last quiet morning before the new job starts. Same hill, same three dogs, still no acknowledgement from any of them." }
];
